permalink   : news/:categories/:year/:title/
markdown    : kramdown

paginate: 2 #6
comments: true
paginate_path: "news/:num"

sass:
  sass_dir: _scss

cover: /assets/images/default-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: KDE 台灣社群
title: KDE 台灣
description: "台灣在地的 KDE 支援社群"
url: http://kde.linux.org.tw
baseurl: ""
domain_name: linux.org.tw
# google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/mug
disqus_shortname: "brli"

author:
  name      : 
  image     : 
  email     : help@linux.org.tw
  url       : http://kde.linux.org.tw/
  facebook  : 
  twitter   : 
  instagram : 
  github    : https://github.com/linux-taiwan/kde.linux.org.tw
  linkedin  : 
  bio       : ""

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
